# Generated by Django 5.2.1 on 2025-06-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(default=1),
        ),
    ]
